# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.4-x86_64"

  config.vm.define :keepalived01 do |node|
    node.vm.hostname = "keepalived01"
    node.vm.network :private_network, ip: "192.168.50.10"
    node.vm.network :private_network, ip: "192.168.51.10"
    node.vm.network :forwarded_port, guest: 80, host: 8080
    node.vm.provision "shell", path: "config.d/keepalived01.sh"
  end

  config.vm.define :keepalived02 do |node|
    node.vm.hostname = "keepalived02"
    node.vm.network :private_network, ip: "192.168.50.11"
    node.vm.network :private_network, ip: "192.168.51.11"
    node.vm.network :forwarded_port, guest: 80, host: 8081
    node.vm.provision "shell", path: "config.d/keepalived02.sh"
  end

  config.vm.define :mysql56 do |node|
    node.vm.hostname = "mysql56"
    node.vm.network :private_network, ip: "192.168.50.12"
    node.vm.network :private_network, ip: "192.168.51.12"
    node.vm.provision "shell", path: "config.d/mysql56.sh"
  end

  config.vm.define :zabbixagent do |node|
    node.vm.hostname = "zabbixagent"
    node.vm.network :private_network, ip: "192.168.50.14"
    node.vm.provision "shell", path: "config.d/zabbixagent.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
