# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.4-x86_64"

  config.vm.define :keepalived01 do |keepalived|
    keepalived.vm.hostname = "keepalived01"
    keepalived.vm.network :private_network, ip: "192.168.50.10"
    keepalived.vm.network :private_network, ip: "192.168.51.10"
    keepalived.vm.provision "shell", path: "bootstrap.d/keepalived01.sh"
  end

  config.vm.define :keepalived02 do |keepalived|
    keepalived.vm.hostname = "keepalived02"
    keepalived.vm.network :private_network, ip: "192.168.50.11"
    keepalived.vm.network :private_network, ip: "192.168.51.11"
    keepalived.vm.provision "shell", path: "bootstrap.d/keepalived02.sh"
  end

  config.vm.define :mysql56 do |mysql|
    mysql.vm.hostname = "mysql56"
    mysql.vm.network :private_network, ip: "192.168.50.12"
    mysql.vm.network :private_network, ip: "192.168.51.12"
    mysql.vm.provision "shell", path: "bootstrap.d/mysql56.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  #config.vm.provision "shell", path: "bootstrap.sh"
end
